# Generated by Django 2.1.5 on 2023-07-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_auto_20230718_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='comentarios',
            new_name='comentario',
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='user',
            new_name='usuario',
        ),
    ]
